# mcp_data_improved.py - FULL & CORRECTED training dataset

TRAINING_COMMANDS = [
    # ======== SAFE Commands (50 examples) ========
    ("ls", "SAFE"),
    ("ls -la", "SAFE"),
    ("ls -la /home", "SAFE"),
    ("echo hello", "SAFE"),
    ("pwd", "SAFE"),
    ("cat file.txt", "SAFE"),
    ("grep pattern file", "SAFE"),
    ("git status", "SAFE"),
    ("git log", "SAFE"),
    ("git log --oneline", "SAFE"),
    ("git pull", "SAFE"),
    ("git fetch", "SAFE"),
    ("git diff", "SAFE"),
    ("docker build .", "SAFE"),
    ("docker ps", "SAFE"),
    ("docker images", "SAFE"),
    ("docker inspect container", "SAFE"),
    ("terraform plan", "SAFE"),
    ("terraform validate", "SAFE"),
    ("terraform show", "SAFE"),
    ("kubectl get pods", "SAFE"),
    ("kubectl get nodes", "SAFE"),
    ("kubectl describe pod my-pod", "SAFE"),
    ("kubectl logs pod-name", "SAFE"),
    ("kubectl get deployment", "SAFE"),
    ("SELECT * FROM users;", "SAFE"),
    ("SELECT COUNT(*) FROM table;", "SAFE"),
    ("SELECT name FROM users WHERE id=1;", "SAFE"),
    ("aws s3 ls", "SAFE"),
    ("aws s3 ls s3://bucket", "SAFE"),
    ("aws ec2 describe-instances", "SAFE"),
    ("aws iam list-users", "SAFE"),
    ("gcloud projects list", "SAFE"),
    ("gcloud compute instances list", "SAFE"),
    ("gcloud sql instances describe", "SAFE"),
    ("npm list", "SAFE"),
    ("npm list -g", "SAFE"),
    ("npm install tailwind", "SAFE"),
    ("npm install express", "SAFE"),
    ("npm install -g typescript", "SAFE"),
    ("pip install numpy", "SAFE"),
    ("pip list", "SAFE"),
    ("yarn install", "SAFE"),
    ("composer install", "SAFE"),
    ("apt-get update", "SAFE"),
    ("apt-get search curl", "SAFE"),
    ("brew list", "SAFE"),
    ("make build", "SAFE"),
    ("cargo build", "SAFE"),
    ("go build", "SAFE"),
    
    # ======== LOW Risk Commands (40 examples) ========
    ("mkdir folder", "LOW"),
    ("mkdir -p backup", "LOW"),
    ("mkdir -p data/logs", "LOW"),
    ("touch file.txt", "LOW"),
    ("touch new_file", "LOW"),
    ("cp file.txt backup.txt", "LOW"),
    ("cp -r src/ backup/", "LOW"),
    ("ln -s source link", "LOW"),
    ("systemctl start apache2", "LOW"),
    ("systemctl start mysql", "LOW"),
    ("systemctl enable nginx", "LOW"),
    ("systemctl restart nginx", "LOW"),
    ("kubectl apply -f manifest.yaml", "LOW"),
    ("kubectl set image deployment/app", "LOW"),
    ("docker build -t myimage .", "LOW"),
    ("docker run -d myimage", "LOW"),
    ("docker pull ubuntu", "LOW"),
    ("docker exec container ls", "LOW"),
    ("git branch new-branch", "LOW"),
    ("git checkout main", "LOW"),
    ("git merge develop", "LOW"),
    ("git tag v1.0", "LOW"),
    ("npm update", "LOW"),
    ("npm audit fix", "LOW"),
    ("npm audit", "LOW"),
    ("pip install --upgrade pip", "LOW"),
    ("pip freeze > requirements.txt", "LOW"),
    ("composer update", "LOW"),
    ("apt-get install curl", "LOW"),
    ("apt-get upgrade", "LOW"),
    ("brew upgrade", "LOW"),
    ("brew install python", "LOW"),
    ("tar -czf backup.tar.gz data/", "LOW"),
    ("tar -xzf backup.tar.gz", "LOW"),
    ("zip -r backup.zip data/", "LOW"),
    ("unzip backup.zip", "LOW"),
    ("scp file.txt user@server:/path", "LOW"),
    ("rsync -av source/ dest/", "LOW"),
    ("chown user:group file", "LOW"),
    ("chmod 755 script.sh", "LOW"),
    
    # ======== MEDIUM Risk Commands (45 examples) ========
    ("rm file.txt", "MEDIUM"),
    ("rm -r directory/", "MEDIUM"),
    ("rm -r src/", "MEDIUM"),
    ("rm *.log", "MEDIUM"),
    ("git reset --hard", "MEDIUM"),
    ("git push --force", "MEDIUM"),
    ("git rebase -i HEAD~5", "MEDIUM"),
    ("git reset HEAD~3", "MEDIUM"),
    ("git clean -fd", "MEDIUM"),
    ("git branch -D branch-name", "MEDIUM"),
    ("kubectl delete pod my-pod", "MEDIUM"),
    ("kubectl delete deployment app", "MEDIUM"),
    ("kubectl scale deployment app --replicas=0", "MEDIUM"),
    ("docker rm container-id", "MEDIUM"),
    ("docker stop container-id", "MEDIUM"),
    ("docker rmi image-id", "MEDIUM"),
    ("docker compose down", "MEDIUM"),
    ("DELETE FROM users WHERE id > 100;", "MEDIUM"),
    ("UPDATE users SET active=0;", "MEDIUM"),
    ("UPDATE products SET price=0;", "MEDIUM"),
    ("DROP TABLE backup;", "MEDIUM"),
    ("ALTER TABLE users DROP COLUMN", "MEDIUM"),
    ("TRUNCATE TABLE logs;", "MEDIUM"),
    ("npm uninstall package", "MEDIUM"),
    ("npm prune", "MEDIUM"),
    ("pip uninstall numpy", "MEDIUM"),
    ("composer remove package", "MEDIUM"),
    ("systemctl stop nginx", "MEDIUM"),
    ("systemctl disable service", "MEDIUM"),
    ("mv file location", "MEDIUM"),
    ("mv -r src/ archive/", "MEDIUM"),
    ("rsync -r --delete source/ dest/", "MEDIUM"),
    ("chmod 644 file.txt", "MEDIUM"),
    ("chmod 755 /var/www", "MEDIUM"),
    ("chown -R user:group /app", "MEDIUM"),
    ("apt-get remove package", "MEDIUM"),
    ("apt-get autoremove", "MEDIUM"),
    ("yum remove package", "MEDIUM"),
    ("pacman -R package", "MEDIUM"),
    ("brew uninstall package", "MEDIUM"),
    ("git stash drop", "MEDIUM"),
    ("git reflog expire", "MEDIUM"),
    ("docker system prune", "MEDIUM"),
    ("find / -name '*.tmp' -delete", "MEDIUM"),
    ("sed -i 's/old/new/g' file.txt", "MEDIUM"),
    
    # ======== HIGH Risk Commands (50 examples) ========
    ("rm -rf /", "HIGH"),
    ("rm -rf /home", "HIGH"),
    ("rm -rf /etc", "HIGH"),
    ("rm -rf /usr", "HIGH"),
    ("rm -rf /var", "HIGH"),
    ("rm -rf ~/Documents", "HIGH"),
    ("rm -rf ..", "HIGH"),
    ("rm -rf /root/*", "HIGH"),
    ("DROP DATABASE prod", "HIGH"),
    ("DROP DATABASE production", "HIGH"),
    ("DROP DATABASE main", "HIGH"),
    ("DROP TABLE users", "HIGH"),
    ("DROP TABLE customers", "HIGH"),
    ("TRUNCATE users", "HIGH"),
    ("TRUNCATE critical_data", "HIGH"),
    ("DELETE FROM users;", "HIGH"),
    ("DELETE FROM customers;", "HIGH"),
    ("chmod 777 /etc/passwd", "HIGH"),
    ("chmod -R 777 /", "HIGH"),
    ("chmod 666 /etc/sudoers", "HIGH"),
    ("shutdown -h now", "HIGH"),
    ("shutdown -r now", "HIGH"),
    ("reboot", "HIGH"),
    ("halt", "HIGH"),
    ("poweroff", "HIGH"),
    ("init 0", "HIGH"),
    ("terraform destroy", "HIGH"),
    ("terraform destroy --auto-approve", "HIGH"),
    ("terraform apply -destroy", "HIGH"),
    ("kubectl delete nodes --all", "HIGH"),
    ("kubectl delete namespace default", "HIGH"),
    ("docker rmi $(docker images -q)", "HIGH"),
    ("docker rm -f $(docker ps -aq)", "HIGH"),
    ("docker system prune -a", "HIGH"),
    ("aws s3 rm s3://bucket --recursive", "HIGH"),
    ("aws s3 rm s3://prod-bucket --recursive", "HIGH"),
    ("aws ec2 terminate-instances --instance-ids i-xxxxx", "HIGH"),
    ("aws rds delete-db-instance --db-instance-identifier prod", "HIGH"),
    ("aws iam delete-user --user-name admin", "HIGH"),
    ("gcloud compute instances delete prod-vm", "HIGH"),
    ("gcloud sql instances delete prod-db", "HIGH"),
    ("gcloud compute disks delete --all", "HIGH"),
    ("git reset --hard HEAD~10", "HIGH"),
    ("git push --force origin main", "HIGH"),
    ("git reset --hard origin/main", "HIGH"),
    ("mkfs /dev/sda1", "HIGH"),
    ("mkfs.ext4 /dev/sda", "HIGH"),
    ("dd if=/dev/zero of=/dev/sda", "HIGH"),

    ("ls /etc", "SAFE"),
("ls /var/log", "SAFE"),
("cat /etc/passwd", "SAFE"),
("cat /var/log/syslog", "SAFE"),
("grep error /var/log/syslog", "SAFE"),
("grep root /etc/passwd", "SAFE"),
("find . -name '*.py'", "SAFE"),
("find /var -type f", "SAFE"),
("du -sh /home", "SAFE"),
("df -h", "SAFE"),
("whoami", "SAFE"),
("who", "SAFE"),
("uptime", "SAFE"),
("top", "SAFE"),
("ps aux", "SAFE"),

# SQL SAFE
("SELECT NOW();", "SAFE"),
("SELECT version();", "SAFE"),
("SELECT id,name FROM customers;", "SAFE"),
("SELECT * FROM logs LIMIT 10;", "SAFE"),
("SELECT COUNT(*) FROM orders;", "SAFE"),

# Git SAFE
("git show", "SAFE"),
("git remote -v", "SAFE"),
("git branch", "SAFE"),
("git stash list", "SAFE"),

# Docker SAFE
("docker stats", "SAFE"),
("docker network ls", "SAFE"),
("docker volume ls", "SAFE"),

# Kubernetes SAFE
("kubectl get services", "SAFE"),
("kubectl get namespaces", "SAFE"),
("kubectl cluster-info", "SAFE"),

# Cloud SAFE
("aws ec2 describe-security-groups", "SAFE"),
("aws iam list-roles", "SAFE"),
("gcloud config list", "SAFE"),

# ================= LOW =================

("mkdir new_project", "LOW"),
("mkdir logs", "LOW"),
("touch index.js", "LOW"),
("touch config.yaml", "LOW"),
("cp config.json config.backup", "LOW"),
("cp -r templates backup_templates", "LOW"),
("ln -s /usr/bin/python python_link", "LOW"),
("systemctl reload nginx", "LOW"),
("service apache2 restart", "LOW"),

# Docker LOW
("docker run ubuntu", "LOW"),
("docker run -it ubuntu bash", "LOW"),
("docker tag image latest", "LOW"),

# Kubernetes LOW
("kubectl apply -f deployment.yaml", "LOW"),
("kubectl rollout restart deployment app", "LOW"),
("kubectl set env deployment/app DEBUG=true", "LOW"),

# Terraform LOW
("terraform init", "LOW"),
("terraform workspace list", "LOW"),

# Git LOW
("git add .", "LOW"),
("git commit -m 'update'", "LOW"),
("git checkout -b feature", "LOW"),

# Package manager LOW
("npm run build", "LOW"),
("npm run start", "LOW"),
("pip install flask", "LOW"),
("pip install pandas", "LOW"),

# ================= MEDIUM =================

("rm temp.txt", "MEDIUM"),
("rm logs.log", "MEDIUM"),
("rm -r cache", "MEDIUM"),
("rm -r build", "MEDIUM"),
("rm -r node_modules", "MEDIUM"),

("mv config.old config.new", "MEDIUM"),
("mv backup.tar.gz archive/", "MEDIUM"),

("chmod 700 secret.txt", "MEDIUM"),
("chmod -R 755 public_html", "MEDIUM"),

("chown root:root file", "MEDIUM"),

# SQL MEDIUM
("DELETE FROM logs WHERE id=10;", "MEDIUM"),
("DELETE FROM sessions WHERE expired=1;", "MEDIUM"),
("UPDATE accounts SET balance=0;", "MEDIUM"),
("UPDATE users SET role='admin' WHERE id=1;", "MEDIUM"),

("DROP INDEX idx_users", "MEDIUM"),
("ALTER TABLE products ADD COLUMN price INT;", "MEDIUM"),

# Docker MEDIUM
("docker stop my_container", "MEDIUM"),
("docker rm old_container", "MEDIUM"),
("docker image rm old_image", "MEDIUM"),

# Kubernetes MEDIUM
("kubectl delete service my-service", "MEDIUM"),
("kubectl delete configmap app-config", "MEDIUM"),

# Git MEDIUM
("git revert HEAD", "MEDIUM"),
("git reset HEAD~1", "MEDIUM"),

# ================= HIGH =================

("rm -rf /*", "HIGH"),
("rm -rf /tmp/*", "HIGH"),
("rm -rf $HOME", "HIGH"),
("rm -rf /var/log", "HIGH"),

# SQL HIGH
("DROP DATABASE users", "HIGH"),
("DROP DATABASE staging", "HIGH"),
("DROP TABLE orders", "HIGH"),
("DROP TABLE payments", "HIGH"),
("TRUNCATE TABLE sessions", "HIGH"),
("TRUNCATE TABLE transactions", "HIGH"),

("DELETE FROM users", "HIGH"),
("DELETE FROM orders", "HIGH"),

# Docker HIGH
("docker container prune -f", "HIGH"),
("docker volume prune -f", "HIGH"),
("docker system prune --volumes", "HIGH"),

# Kubernetes HIGH
("kubectl delete deployment --all", "HIGH"),
("kubectl delete pods --all", "HIGH"),
("kubectl delete services --all", "HIGH"),

# Terraform HIGH
("terraform destroy -auto-approve", "HIGH"),

# AWS HIGH
("aws ec2 terminate-instances --instance-ids i-123", "HIGH"),
("aws rds delete-db-instance prod-db", "HIGH"),
("aws s3 rb s3://prod-bucket --force", "HIGH"),

# GCP HIGH
("gcloud compute instances delete --all", "HIGH"),
("gcloud sql instances delete prod-db", "HIGH"),

# Filesystem destruction
("mkfs.ext4 /dev/sdb", "HIGH"),
("mkfs /dev/sdb1", "HIGH"),
("dd if=/dev/zero of=/dev/sdb", "HIGH"),

]

LABELS = ["SAFE", "LOW", "MEDIUM", "HIGH"]